version: "3.9"
services:
  php:
    container_name: php
    build: ./web/
    depends_on:
      - mysqlDB
    ports:
      - "${PORT}:80"
    volumes: 
      - ./web/src:/var/www/html/:ro
    environment:
      MYSQL_PASSWORD: "${SQL_DBPASS}"
      MYSQL_USER: "${SQL_USER}"
      MYSQL_DATABASE: "${SQL_DBNAME}"
      MYSQL_HOST: "mysqlDB"
      MYSQL_PORT: "${SQL_PORT}"
      HOST_NAME: "${HOST_NAME}"
      PORT: "${PORT}"

  nodejs:
    container_name: socketjs
    build: ./webSocket/
    ports:
      - "${WS_PORT}:8000"
    environment:
      PHP_HOST: "php"

  mysqlDB:
    container_name: mysql
    image: mysql:latest
    restart: always
    command: --default_authentication_plugin=mysql_native_password
    volumes:
      - ./db-data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.data
    environment:
      MYSQL_ROOT_PASSWORD: "${SQL_ROOTPASS}"
      MYSQL_PASSWORD: "${SQL_DBPASS}"
      MYSQL_USER: "${SQL_USER}"
      MYSQL_DATABASE: "${SQL_DBNAME}"
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'