version: "3.9"
services:
  php:
    container_name: php
    build: .
    depends_on:
      - mysqlDB
    ports:
      - "${PORT}:80"
    volumes: 
      - ./web/:/var/www/html/:ro
    environment:
      MYSQL_PASSWORD: "123"
      MYSQL_USER: "${SQL_USER}"
      MYSQL_DATABASE: "${SQL_DBNAME}"
      MYSQL_HOST: "mysqlDB"
      HOST_NAME: "${HOST_NAME}"


  mysqlDB:
    container_name: mysql
    image: mysql:latest
    restart: always
    command: --default_authentication_plugin=mysql_native_password
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.data
      - presistent:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_PASSWORD: "123"
      MYSQL_USER: "${SQL_USER}"
      MYSQL_DATABASE: "${SQL_DBNAME}"
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'
    
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_PASSWORD: "123"
      PMA_USER: "root"
      PMA_HOST: "mysqlDB"

volumes:
  presistent:
